### ISSUE TITLE
Downloading fails with a "No such file or directory" from youtube-dl

### ISSUE THREAD

**Issue by beerendlauwers** [yoonwaiyan/stackskills-dl#30]
I'm trying to download this lecture: https://stackskills.com/courses/sparkwords/lectures/1496358

Here's the full error dump:

```
Downloading I_HAVE_A_SECRET_TO_TELL_YOU
/home/beerend/stackskills-dl-master/lib/lecture.rb:57:in ``': No such file or directory - youtube-dl (Errno::ENOENT)
	from /home/beerend/stackskills-dl-master/lib/lecture.rb:57:in `download_video'
	from /home/beerend/stackskills-dl-master/lib/lecture.rb:37:in `block in download'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:13:in `block in mkchdir'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:12:in `chdir'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:12:in `mkchdir'
	from /home/beerend/stackskills-dl-master/lib/lecture.rb:36:in `download'
	from /home/beerend/stackskills-dl-master/lib/course.rb:24:in `block (2 levels) in download'
	from /home/beerend/stackskills-dl-master/lib/course.rb:23:in `each'
	from /home/beerend/stackskills-dl-master/lib/course.rb:23:in `block in download'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:13:in `block in mkchdir'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:12:in `chdir'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:12:in `mkchdir'
	from /home/beerend/stackskills-dl-master/lib/course.rb:22:in `download'
	from /home/beerend/stackskills-dl-master/lib/course_finder.rb:13:in `block (2 levels) in run'
	from /home/beerend/stackskills-dl-master/lib/course_finder.rb:41:in `block in execute'
	from /home/beerend/stackskills-dl-master/lib/course_finder.rb:36:in `each'
	from /home/beerend/stackskills-dl-master/lib/course_finder.rb:36:in `execute'
	from /home/beerend/stackskills-dl-master/lib/course_finder.rb:12:in `block in run'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:13:in `block in mkchdir'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:12:in `chdir'
	from /home/beerend/stackskills-dl-master/lib/utilities.rb:12:in `mkchdir'
	from /home/beerend/stackskills-dl-master/lib/course_finder.rb:11:in `run'
	from stackskills_dl.rb:11:in `<main>'
```

I can send you the HTML source via e-mail for further debugging if this can help you, just send me an e-mail at beerendlauwers@gmail.com.

**Comment by yoonwaiyan** [comment]
Are you using Windows?

**Comment by beerendlauwers** [comment]
Sorry, forgot to mention that. Ubuntu 16.04.

**Comment by ghost** [comment]
Same issue with me Ubuntu on 16.04

**Comment by yoonwaiyan** [comment]
Hi, sorry for the slow response. Can I confirm that youtube-dl is installed and executable in your stackskills-dl directory?

**Comment by yoonwaiyan** [comment]
I'm closing this issue for now as there's no response, feel free to re-open if there's any new findings on this issue.

**Comment by beerendlauwers** [comment]
Hi @yoonwaiyan, `youtube-dl` was probably not installed since this was on a relatively fresh install of Ubuntu 16.04. I was confused because it had already downloaded the majority of the videos of the course. I'll try it with `youtube-dl`installed later today.
