### ISSUE TITLE
Not working,

### ISSUE THREAD

**Issue by darkjedeye** [yoonwaiyan/stackskills-dl#40]

**Comment by darkjedeye** [comment]
I have installed this system as described, and get this in return,

```
Loaded login credentials from environment variables.
/usr/local/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
        from /usr/local/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
        from /usr/local/lib/ruby/2.4.0/net/http.rb:948:in `connect'
        from /usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
        from /usr/local/lib/ruby/2.4.0/net/http.rb:882:in `start'
        from /usr/local/bundle/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
        from /usr/local/bundle/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
        from /usr/local/bundle/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
        from /usr/local/bundle/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:267:in `fetch'
        from /usr/local/bundle/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:986:in `response_redirect'
        from /usr/local/bundle/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:308:in `fetch'
        from /usr/local/bundle/gems/mechanize-2.7.4/lib/mechanize.rb:464:in `get'
        from /usr/app/lib/course_finder.rb:28:in `execute'
        from /usr/app/lib/course_finder.rb:12:in `block in run'
        from /usr/app/lib/utilities.rb:13:in `block in mkchdir'
        from /usr/app/lib/utilities.rb:12:in `chdir'
        from /usr/app/lib/utilities.rb:12:in `mkchdir'
        from /usr/app/lib/course_finder.rb:11:in `run'
        from stackskills_dl.rb:11:in `<main>'
```

Where am i going wrong?

**Comment by yoonwaiyan** [comment]
Hi, try change line 26 of `lib/course_finder.rb` to `@agent = Mechanize.new { |a| a.ssl_version = :TLSv1 }` and run again. Please let me know whether this works, thanks.

**Comment by yoonwaiyan** [comment]
Since there's no reply I'll close this issue for now. Feel free to re-open if there's any update.
