### ISSUE TITLE
Net::HTTPInternalServerError

### ISSUE THREAD

**Issue by linux95** [yoonwaiyan/stackskills-dl#41]
Receiving the following error when trying to d/l stackskills course:
```
/home/dmiller/.gem/ruby/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:316:in `fetch': 500 => Net::HTTPInternalServerError for https://stackskills.com/courses/116320/lectures/1707277 -- unhandled response (Mechanize::ResponseCodeError)
        from /home/dmiller/.gem/ruby/gems/mechanize-2.7.4/lib/mechanize.rb:464:in `get'
        from /home/dmiller/.gem/ruby/gems/mechanize-2.7.4/lib/mechanize.rb:373:in `click'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:121:in `block (2 levels) in analyze_course'
        from /home/dmiller/.gem/ruby/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:190:in `block in each'
        from /home/dmiller/.gem/ruby/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `upto'
        from /home/dmiller/.gem/ruby/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `each'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:119:in `block in analyze_course'
        from /home/dmiller/.gem/ruby/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:190:in `block in each'
        from /home/dmiller/.gem/ruby/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `upto'
        from /home/dmiller/.gem/ruby/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `each'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:114:in `each_with_index'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:114:in `analyze_course'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:38:in `block in execute'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:36:in `each'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:36:in `execute'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:12:in `block in run'
        from /home/dmiller/stackskills-dl/lib/utilities.rb:13:in `block in mkchdir'
        from /home/dmiller/stackskills-dl/lib/utilities.rb:12:in `chdir'
        from /home/dmiller/stackskills-dl/lib/utilities.rb:12:in `mkchdir'
        from /home/dmiller/stackskills-dl/lib/course_finder.rb:11:in `run'
        from stackskills_dl.rb:11:in `<main>'
```
This appears to be a new error as I just downloaded a course several days ago. Please advise. Thank you

**Comment by linux95** [comment]
yoonwaiyan,
  It appears this error maybe something on Stackskills site. I went back an attempted to download the courses and everything worked as normal. It may have been something that they were doing on their site since I noticed a change in their formatting. However, please close this as it does not appear to be an error with your application. As always, thanks so much for your time and effort with this app.

**Comment by yoonwaiyan** [comment]
@linux95 sorry for not being responsive enough recently. I agree with you that a recent change of formatting could break the script, which I have yet verify it but it seems to be working fine. Much thanks for your update!
