### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by flatlinebb** [yoonwaiyan/stackskills-dl#64]
```
$ docker-compose run stackskills_dl
Loaded login credentials from environment variables.
/usr/local/bundle/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:316:in `fetch': 503 => Net::HTTPServiceUnavailable for https://sso.teachable.com/secure/1453/users/sign_in?clean_login=true&reset_purchase_session=1 -- unhandled response (Mechanize::ResponseCodeError)
        from /usr/local/bundle/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:986:in `response_redirect'
        from /usr/local/bundle/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:308:in `fetch'
        from /usr/local/bundle/gems/mechanize-2.7.4/lib/mechanize.rb:464:in `get'
        from /usr/app/lib/course_finder.rb:28:in `execute'
        from /usr/app/lib/course_finder.rb:12:in `block in run'
        from /usr/app/lib/utilities.rb:13:in `block in mkchdir'
        from /usr/app/lib/utilities.rb:12:in `chdir'
        from /usr/app/lib/utilities.rb:12:in `mkchdir'
        from /usr/app/lib/course_finder.rb:11:in `run'
        from stackskills_dl.rb:11:in `<main>'
```

Any suggestions what to try?

**Comment by yoonwaiyan** [comment]
Hi there, it's a known issue and being reported on https://github.com/yoonwaiyan/stackskills-dl/issues/51 . I'll try a different approach to fix the login issue. I'm closing this issue, feel free to comment in the issue as mentioned, thanks.
